// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthwindSystem.Entities;

[Index("LastName", Name = "LastName")]
[Index("PostalCode", Name = "PostalCode")]
internal partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(20)]
    public string LastName { get; set; }

    [Required]
    [StringLength(10)]
    public string FirstName { get; set; }

    [StringLength(30)]
    public string Title { get; set; }

    [StringLength(25)]
    public string TitleOfCourtesy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? HireDate { get; set; }

    [StringLength(60)]
    public string Address { get; set; }

    [StringLength(15)]
    public string City { get; set; }

    [StringLength(15)]
    public string Region { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    [StringLength(15)]
    public string Country { get; set; }

    [StringLength(24)]
    public string HomePhone { get; set; }

    [StringLength(4)]
    public string Extension { get; set; }

    [Column(TypeName = "image")]
    public byte[] Photo { get; set; }

    [Column(TypeName = "ntext")]
    public string Notes { get; set; }

    public int? ReportsTo { get; set; }

    [StringLength(255)]
    public string PhotoPath { get; set; }

    [InverseProperty("ReportsToNavigation")]
    public virtual ICollection<Employee> InverseReportsToNavigation { get; set; } = new List<Employee>();

    [InverseProperty("Employee")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [ForeignKey("ReportsTo")]
    [InverseProperty("InverseReportsToNavigation")]
    public virtual Employee ReportsToNavigation { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Employees")]
    public virtual ICollection<Territory> Territories { get; set; } = new List<Territory>();
}