// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthwindSystem.Entities;

[Table("Region")]
internal partial class Region
{
    [Key]
    public int RegionID { get; set; }

    [Required]
    [StringLength(50)]
    public string RegionDescription { get; set; }

    [InverseProperty("Region")]
    public virtual ICollection<Territory> Territories { get; set; } = new List<Territory>();
}